apiVersion: v1
kind: Service
metadata:
  name: coworking-api
spec:
  selector:
    app.kubernetes.io/name: coworking-api
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153